#! /bin/bash

NETWORK=$1

echo 'y' | gcloud compute instance-groups managed delete $NETWORK-servers \
	--zone us-central1-a
echo 'y' | gcloud compute firewall-rules delete $NETWORK-allow-node
echo 'y' | gcloud compute instance-templates delete $NETWORK-template
echo 'y' | gcloud compute images delete $NETWORK-image
echo 'y' | gcloud compute snapshots delete $NETWORK-snapshot
