#! /bin/bash

FILTER=$1

gcloud compute firewall-rules list \
	--filter $FILTER \
	--format "table(
	name,
        targetTags.list():label=TARGET_TAGS,
        direction,
	sourceRanges.list():label=SRC_RANGES,
        sourceTags.list():label=SRC_TAGS,
        destinationRanges.list():label=DEST_RANGES,
	allowed[].map().firewall_rule().list():label=ALLOW,
	denied[].map().firewall_rule().list():label=DENY,
	priority,
	network,
	disabled
	)"
